const dieSound = new Audio('/sound/die.mp3')
const eatFruitSound = new Audio('/sound/eat-fruit.mp3')
const eatGhostSound = new Audio('/sound/eat-ghost.mp3')
const eatPillSound = new Audio('/sound/eat-pill.mp3')
const extraLifeSound = new Audio('/sound/extra-life.mp3')
const ghostEatenSound = new Audio('/sound/ghost-eaten.mp3')
const eatingSound = new Audio('/sound/eating.mp3')
const readySound = new Audio('/sound/ready.mp3')
const sirenSound = new Audio('/sound/siren.mp3')
const wazaSound = new Audio('/sound/waza.mp3')

export const playDieSound = () => dieSound.play()
export const playEatFruitSound = () => eatFruitSound.play()
export const playEatGhostSound = () => eatGhostSound.play()
export const playEatPillSound = () => eatPillSound.play()
export const playExtraLifeSound = () => extraLifeSound.play()
export const playGhostEatenSound = () => ghostEatenSound.play()
export const playEatingSound = () => eatingSound.play()
export const playReadySound = () => readySound.play()
export const playSirenSound = () => sirenSound.play()
export const playWazaSound  = () => wazaSound.play()
